### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [Lexcorp3439/bloom-filter#1]
1. Массив `bool` не самое удачное решение для битовых масок: занимает слишком много места. Можно хранить битовые маски компактнее, используя массив `unsigned int` и выставляя отдельные биты каждой ячейки. 

2.

> Не предоставляется возможным потребовать от пользователя K независимых хэш-функций. Поэтому для получения любого количества хэшей ьудем использовать формулу: (hashA + k * hashB) % M

Не очень понятно, почему: можно взять и потребовать. Длина уже известна при создании фильтра. Можно требовать от пользователя либо массив функций для хэширования, либо функцию, возвращающую массив из нужного числа хэшей (как это делает murmur для 128-битного хэша). Зависимые хэши ломают всю идею фильтра Блума. Если hashA и hashB совпадают для разных объектов, то для всех их possibly contains будет true, если хотя бы один такой объект был добавлен.

**Comment by gagarski** [comment]
По отчёту: оформите пожалуйста ещё лист с заданием на курсовой проект (форма была в одном из документов, которые я высылал на общуюю почту).

**Comment by gagarski** [comment]
В любом случае, готов завтра обсуждать ваше проект.

**Comment by Lexcorp3439** [comment]
Дело в том, что пользователь ведь не знает сколько функций ему надо. Он конечно может сам посчитать, либо делать дополнительную функцию, которая вернет ему это число

**Comment by Lexcorp3439** [comment]
И на сколько я знаю, тот метод, который я использовал, не влияет на вероятность ложных срабатываний. Это вроде как как-то доказывается, если смогу найти доказательство, я его приложу

**Comment by gagarski** [comment]
> Дело в том, что пользователь ведь не знает сколько функций ему надо. Он конечно может сам посчитать, либо делать дополнительную функцию, которая вернет ему это число.

Смысла в функции особо нет, пользователю всё равно придётся писать кучу хэш-функций на этапе написания программы (а функцию он сможет вызвать только запустив её). Единственный выход, это сказать ему формулу для количества хэш функций и требовать от него, чтобы именно столько он их и передал при создании фильтра.

**Comment by gagarski** [comment]
> (hashA + k * hashB) % M

При одинаковых hashA и hashB, набор хэшей, полученных по этой формуле будет одинаковым, разве нет? Ложноположительное срабатывание таким образом не отмести.

**Comment by gagarski** [comment]
> Единственный выход, это сказать ему формулу для количества хэш функций и требовать от него, чтобы именно столько он их и передал при создании фильтра.

Как вариант, можно разрешить пользователю передавать любое число хэш-функций (пусто он сам задаёт количество), а формулу для оптимального числа считать рекомендуемой (заботу об оптимальности возложить на пользователя).

**Comment by Lexcorp3439** [comment]
> > (hashA + k * hashB) % M
> 
> При одинаковых hashA и hashB, набор хэшей, полученных по этой формуле будет одинаковым, разве нет? Ложноположительное срабатывание таким образом не отмести.

Ну это нужно проверить, может ли murmurHash вернуть такой 128-битный хэш, чтоб оба 64-битных числа были одинаковыми. Мне кажется что это уж слишком маловероятно, ибо именно такой подход для данного алгоритма хэширования я наблюдал неоднократно для реализация данной структуры данных.

**Comment by Lexcorp3439** [comment]
Как я понимаю, оба значения хэша от данного алгоритма независимы друг от друга, поэтому одинаковые значения не могут возникнуть.

**Comment by Lexcorp3439** [comment]
Даже если не нравится конкретно такая реализация, можно реализовать свои 2 независимых хэш-функции и воспользоваться тем же методом. Тогда набор хэшей будет разным 100%. И опять же не потребуется просить от пользователя самому задавать хэш функции.  Но мне все равно кажется, что реализация murmurhash очень хорошо подходит для данной задачи

**Comment by gagarski** [comment]
Я не про совпадающие hashA и hashB (они вроде как действительно независимы, с ними всё ок), а про случай, если для двух `void*` эти два хэша совпадут. Разумеется, вероятность не очень велика, но мощность множества объектов, представляемых `void*` гораздо больше чем 2^128. Именно поэтому в фильтрах Блума и используют большое количество независимых хэш-функций, а у вас, по сути, они все зависимы от двух хэш-функций.

**Comment by gagarski** [comment]
> Даже если не нравится конкретно такая реализация, можно реализовать свои 2 независимых хэш-функции и воспользоваться тем же методом. Тогда набор хэшей будет разным 100%. И опять же не потребуется просить от пользователя самому задавать хэш функции. Но мне все равно кажется, что реализация murmurhash очень хорошо подходит для данной задачи

Ещё раз: два хэша от murmurhash действительно независимы, тут сомнений нет. А хэш-функции, используемые в фильтре Блума у вас вполне определённым образом зависимы только от этих двух хэшей.

**Comment by Lexcorp3439** [comment]
Ну в таком случае я уже писал выше, что есть какая-то теорема вроде как, которая говорит, что двойное хеширование может использоваться, чтобы генерировать k значения хэш-функции, не влияя на вероятность ложно-положительного результата

**Comment by Lexcorp3439** [comment]
А метод двойного хеширования как раз и заключается в том подходе, который я реализовал (посмотрел на сайте ИТМО в методах разрешения коллизий)

**Comment by Lexcorp3439** [comment]
Если я все правильно понял, то метод двойного хэширования с независимыми хэш функциями образует универсальную хэш-функцию с помощью которой можно генерировать k различных хэш функций. Так как у murmurhash хорошее равномерное распределение, то мы с равномерным распределением берем какую-то функцию из семейства, и вероятность совпадения равна 1 / М, где М - размер семейства.

**Comment by Lexcorp3439** [comment]
Разве нет?

**Comment by gagarski** [comment]
По моим экспериментам есть ощущение, что это работает, хотя в голове плохо укладывается. Приведёте ссылку на эту теорему?

Ну и битовые поля вместо массива bool остаются актуальными.
